// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "wallet/internal/entity"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// TransactionRepo is an autogenerated mock type for the transactionRepo type
type TransactionRepo struct {
	mock.Mock
}

// Exists provides a mock function with given fields: _a0, _a1, _a2
func (_m *TransactionRepo) Exists(_a0 context.Context, _a1 pgx.Tx, _a2 *entity.Transaction) (bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *entity.Transaction) (bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *entity.Transaction) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, *entity.Transaction) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1, _a2
func (_m *TransactionRepo) Insert(_a0 context.Context, _a1 pgx.Tx, _a2 *entity.Transaction) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *entity.Transaction) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepo creates a new instance of TransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepo {
	mock := &TransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
